export CUDA_VISIBLE_DEVICES=3,1,4,7
python /data/dyl/ReTATSF/run_ReTATSF_weather.py \
        --random_seed 2025 \
        --is_training 1 \
        --root_path './dataset' \
        --TS_data_path 'Weather_captioned/weather_2014-18_nc.parquet' \
        --QT_data_path 'QueryTextPackage.parquet' \
        --NewsDatabase_path 'NewsDatabase-embedding-paraphrase-MiniLM-L6-v2' \
        --features 'M' \
        --checkpoints './M_checkpoints/' \
        --target_ids "Tdew (degC)" "rh (%)" "VPmax (mbar)" "VPact (mbar)" "VPdef (mbar)" "sh (g_kg)" "H2OC (mmol_mol)" "rho (g_m**3)" "wv (m_s)" "max. wv (m_s)" "wd (deg)" "rain (mm)" "raining (s)" "SWDR (W_m2)" "PAR (umol_m2_s)" "max. PAR (umol_m2_s)" "Tlog (degC)" "CO2 (ppm)"\
        --use_multi_gpu \
        --batch_size 64 \
        --num_data 6500 \
        --patience 30 \
        --train_epochs 50 \
        --devices '0,1,2,3' \
        --use_gpu True \
        --gpu 0 \
        --nperseg 30 \
        --nref 5 \
        --naggregation 3 \
        --nref_text 6 \
        --seq_len 60 \
        --pred_len 14 \
        --stride 8 \
        --learning_rate 0.0001 \
        --itr 1 \
        --num_workers 2 \
        --pct_start 0.3 \
        --lradj 'type3'